identifier:        FancyCorp-Demo/tf-workspace-hcp-vault
working_directory: "config-azure"

tags:
- vault
- hcp
- platform:hcp
project: Vault

upstream_workspaces:
- vault-config-bootstrap

auto_apply: true
assessments_enabled: true

creds:
- azure

# We need to be an owner of the Subscription, so we can manage permissions on newly created things
azure_role_definition_name: Owner

# We also need some AAD permissions
azuread_graph_permissions:
- Application.ReadWrite.OwnedBy
- AppRoleAssignment.ReadWrite.All
