identifier:        FancyCorp-Demo/tf-workspace-hcp-vault
working_directory: "config-aws"

tags:
- vault
- hcp
- platform:hcp
project: Vault

# For now, while Run Triggers don't auto-apply, keep this disablked
# TODO: enable when Run Triggers can auto-apply
#upstream_workspaces:
#- vault-config-bootstrap

auto_apply: true
assessments_enabled: true

creds:
- aws
