identifier:        FancyCorp-Demo/tf-workspace-hcp-vault
working_directory: "config-aws"

tags:
- vault
- hcp
- platform:hcp
project: Vault

upstream_workspaces:
- vault-config-bootstrap

auto_apply: true
assessments_enabled: true

creds:
- aws
